rem net start "EmailSender"
net start "EmailDevino"
rem net start "SmsSender"
net start "SmsDevinoSender"
net start "ViberDevinoSender"
rem net start "ViberSmsDevinoSender"
net start "VKBotSender"
net start "TGBotSender"
net start "ViberBotSender"
net start "StatusDevinoPerformer"
