//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid UserId { get; set; }
        public System.Guid UponUserId { get; set; }
        public string Text { get; set; }
    
        public virtual User User { get; set; }
        public virtual User UponUser { get; set; }
    }
}
