//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.ToUsers = new HashSet<User>();
            this.LastDeliveredEvent = new HashSet<User>();
        }
    
        public long Id { get; set; }
        public System.DateTime Tm { get; set; }
        public int EventTypeId { get; set; }
        public System.Guid CausedByUserId { get; set; }
        public Nullable<System.Guid> MsgId { get; set; }
        public Nullable<int> CausedByUserTransportTypeId { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual Message Message { get; set; }
        public virtual Transport CausedByUserTransport { get; set; }
        public virtual User CausedByUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> ToUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> LastDeliveredEvent { get; set; }
    }
}
