//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Members = new HashSet<GroupMember>();
        }
    
        public System.Guid Id { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsEqual { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual User CreatedBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMember> Members { get; set; }
    }
}
