//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageStatsGroupedView
    {
        public System.Guid MsgId { get; set; }
        public int MessageTypeId { get; set; }
        public System.Guid FromUserId { get; set; }
        public Nullable<int> RecipientCount { get; set; }
        public Nullable<int> WebChatCount { get; set; }
        public Nullable<int> FailedCount { get; set; }
        public Nullable<int> SentCount { get; set; }
        public Nullable<int> QuequedCount { get; set; }
        public Nullable<int> WebChatAcceptedCount { get; set; }
        public Nullable<int> SmsUrlOpenedCount { get; set; }
        public long MsgIdx { get; set; }
        public Nullable<int> CantSendToWebChatCount { get; set; }
    }
}
