//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTransportId
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessageTransportId()
        {
            this.Index = 0;
            this.Count = 1;
        }
    
        public long Id { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public string TransportId { get; set; }
        public System.Guid MsgId { get; set; }
        public Nullable<System.Guid> ToUserId { get; set; }
        public int TransportTypeId { get; set; }
        public byte Index { get; set; }
        public byte Count { get; set; }
    
        public virtual TransportType TransportType { get; set; }
        public virtual Message Message { get; set; }
        public virtual MessageToUser MessageToUser { get; set; }
    }
}
