//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageToUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessageToUser()
        {
            this.MessageError = new HashSet<MessageError>();
            this.MessageTransportId = new HashSet<MessageTransportId>();
            this.WebChatDeepLink = new HashSet<WebChatDeepLink>();
        }
    
        public System.Guid MsgId { get; set; }
        public System.Guid ToUserId { get; set; }
        public int ToTransportTypeId { get; set; }
        public bool IsFailed { get; set; }
        public bool IsSent { get; set; }
        public bool IsDelivered { get; set; }
        public bool IsRead { get; set; }
        public long Idx { get; set; }
        public bool IsWebChatGreeting { get; set; }
    
        public virtual Transport ToTransport { get; set; }
        public virtual Message Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageError> MessageError { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageTransportId> MessageTransportId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebChatDeepLink> WebChatDeepLink { get; set; }
    }
}
