//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageError
    {
        public long Id { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public Nullable<System.Guid> MsgId { get; set; }
        public Nullable<System.Guid> ToUserId { get; set; }
        public Nullable<int> ToTransportTypeId { get; set; }
        public string Type { get; set; }
        public string Descr { get; set; }
        public string Trace { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual MessageToUser MessageToUser { get; set; }
    }
}
