//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.Event = new HashSet<Event>();
            this.Answers = new HashSet<Message>();
            this.ToUsers = new HashSet<MessageToUser>();
            this.MessageError = new HashSet<MessageError>();
            this.MessageTransportId = new HashSet<MessageTransportId>();
            this.MessageToSegment = new HashSet<MessageToSegment>();
            this.ForwardByMsg = new HashSet<Message>();
            this.MessageToSelection = new HashSet<MessageToSelection>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime PostTm { get; set; }
        public int MessageTypeId { get; set; }
        public System.Guid FromUserId { get; set; }
        public int FromTransportTypeId { get; set; }
        public Nullable<System.Guid> AnswerToId { get; set; }
        public string Text { get; set; }
        public bool IsDeleted { get; set; }
        public string Specific { get; set; }
        public Nullable<System.Guid> ForwardMsgId { get; set; }
        public Nullable<System.Guid> FileId { get; set; }
        public long Idx { get; set; }
        public bool NeedToChangeText { get; set; }
        public Nullable<System.DateTime> DelayedStart { get; set; }
        public Nullable<System.DateTime> DalayedCancelled { get; set; }
        public Nullable<int> ScenarioStepId { get; set; }
    
        public virtual MessageType MessageType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Answers { get; set; }
        public virtual Message AnswerTo { get; set; }
        public virtual Transport FromTransport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageToUser> ToUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageError> MessageError { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageTransportId> MessageTransportId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageToSegment> MessageToSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> ForwardByMsg { get; set; }
        public virtual Message ForwardMsg { get; set; }
        public virtual FileInfo FileInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageToSelection> MessageToSelection { get; set; }
        public virtual ScenarioStep ScenarioStep { get; set; }
    }
}
