//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageToSelection
    {
        public long Idx { get; set; }
        public System.Guid MsgId { get; set; }
        public System.Guid UserId { get; set; }
        public bool WithStructure { get; set; }
        public bool Include { get; set; }
        public Nullable<int> StructureDeep { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual User User { get; set; }
    }
}
