//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageStatsRowsView
    {
        public System.Guid MsgId { get; set; }
        public int MessageTypeId { get; set; }
        public System.Guid FromUserId { get; set; }
        public Nullable<System.Guid> ToUserId { get; set; }
        public Nullable<int> ToTransportTypeId { get; set; }
        public int IsWebChat { get; set; }
        public int IsFailed { get; set; }
        public int IsSent { get; set; }
        public int IsQuequed { get; set; }
        public int IsWebChatAccepted { get; set; }
        public int IsSmsUrlOpened { get; set; }
        public long MsgIdx { get; set; }
        public int CantSendToWebChat { get; set; }
    }
}
