//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioProcess
    {
        public System.Guid UserId { get; set; }
        public int TransportTypeId { get; set; }
        public int ScenarioStepId { get; set; }
    
        public virtual ScenarioStep ScenarioStep { get; set; }
        public virtual TransportType TransportType { get; set; }
        public virtual User User { get; set; }
    }
}
