//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructureNodeSegment
    {
        public System.Guid NodeId { get; set; }
        public System.Guid SegmentId { get; set; }
        public short Order { get; set; }
        public bool IsBelongToNode { get; set; }
    
        public virtual Segment Segment { get; set; }
        public virtual StructureNode StructureNode { get; set; }
    }
}
