//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public System.Guid UserId { get; set; }
        public long KeyId { get; set; }
        public string Data { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserDataKey UserDataKey { get; set; }
    }
}
