//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Enabled = true;
            this.AuthToken = new HashSet<AuthToken>();
            this.Transports = new HashSet<Transport>();
            this.Contacts = new HashSet<User>();
            this.IncludeToContacts = new HashSet<User>();
            this.ChildUsers = new HashSet<User>();
            this.CausedEvents = new HashSet<Event>();
            this.Events = new HashSet<Event>();
            this.CreatedGroups = new HashSet<Group>();
            this.Groups = new HashSet<GroupMember>();
            this.Segments = new HashSet<Segment>();
            this.Comments = new HashSet<Comment>();
            this.CommentsOnMe = new HashSet<Comment>();
            this.AddresseeForUsers = new HashSet<Transport>();
            this.Files = new HashSet<FileInfo>();
            this.MessageToSelection = new HashSet<MessageToSelection>();
            this.BroadcastProhibitionBy = new HashSet<User>();
            this.BroadcastProhibition = new HashSet<User>();
            this.ScenarioProcess = new HashSet<ScenarioProcess>();
            this.UserData = new HashSet<UserData>();
            this.MatchedPhonesSender = new HashSet<User>();
            this.MatchedPhonesAddr = new HashSet<User>();
            this.PersonalProhibitionMain = new HashSet<User>();
            this.PersonalProhibitionSlave = new HashSet<User>();
        }
    
        public System.Guid Id { get; set; }
        public bool Enabled { get; set; }
        public string FullName { get; set; }
        public bool IsConsultant { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> SignUpDate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string PswHash { get; set; }
        public Nullable<System.Guid> OwnerUserId { get; set; }
        public Nullable<int> DefaultTransportTypeId { get; set; }
        public Nullable<System.DateTime> AvatarUploadDate { get; set; }
        public bool IsTemporary { get; set; }
        public bool IsBot { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<decimal> LoBonusScores { get; set; }
        public Nullable<decimal> OlgBonusScores { get; set; }
        public Nullable<decimal> GoBonusScores { get; set; }
        public Nullable<System.DateTime> LastGetEvents { get; set; }
        public Nullable<int> FLUserNumber { get; set; }
        public Nullable<int> ParentFLUserNumber { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> CityId { get; set; }
        public bool EmailPermission { get; set; }
        public bool SmsPermission { get; set; }
        public bool IsDirector { get; set; }
        public Nullable<System.DateTime> LastOrderDate { get; set; }
        public Nullable<int> PeriodsWolo { get; set; }
        public Nullable<decimal> CashBackBalance { get; set; }
        public Nullable<decimal> FLClubPoints { get; set; }
        public Nullable<decimal> FLClubPointsBurn { get; set; }
        public bool DontDisableOnUpdateStructure { get; set; }
        public bool IsUseDeepChilds { get; set; }
        public Nullable<System.DateTime> LastImportDate { get; set; }
        public string ForeignId { get; set; }
        public string ForeignOwnerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthToken> AuthToken { get; set; }
        public virtual SmsCode SmsCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport> Transports { get; set; }
        public virtual Transport TransportDef { get; set; }
        public virtual UserAvatar UserAvatar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> IncludeToContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> ChildUsers { get; set; }
        public virtual User OwnerUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> CausedEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Event LastDeliveredEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> CreatedGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMember> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Segment> Segments { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual UserSentry UserSentry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> CommentsOnMe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport> AddresseeForUsers { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileInfo> Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageToSelection> MessageToSelection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> BroadcastProhibitionBy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> BroadcastProhibition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioProcess> ScenarioProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserData> UserData { get; set; }
        public virtual ICollection<User> MatchedPhonesSender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> MatchedPhonesAddr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> PersonalProhibitionMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> PersonalProhibitionSlave { get; set; }
    }
}
