//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAvatar
    {
        public System.Guid UserId { get; set; }
        public byte[] Data { get; set; }
        public int MediaTypeId { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    
        public virtual User User { get; set; }
        public virtual MediaType MediaType { get; set; }
    }
}
