//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebChatDeepLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebChatDeepLink()
        {
            this.AcceptedTransportType = new HashSet<TransportType>();
        }
    
        public long Id { get; set; }
        public System.Guid MsgId { get; set; }
        public System.Guid ToUserId { get; set; }
        public int ToTransportTypeId { get; set; }
        public string Link { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public Nullable<int> SentTo { get; set; }
        public Nullable<int> ViberStatus { get; set; }
        public Nullable<int> SmsStatus { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public bool WebFormRequested { get; set; }
        public bool IsFinished { get; set; }
    
        public virtual MessageToUser MessageToUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportType> AcceptedTransportType { get; set; }
        public virtual TransportType SentToTransport { get; set; }
    }
}
