//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLChat.PDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportLog
    {
        public long Id { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public int TransportTypeId { get; set; }
        public bool Outcome { get; set; }
        public string Url { get; set; }
        public string Method { get; set; }
        public string Request { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string Response { get; set; }
        public string Exception { get; set; }
        public Nullable<int> TaskId { get; set; }
    }
}
