use [FLChat]
go

DROP INDEX [UNQ__UsrUser_Email] ON [Usr].[User]
GO

DROP INDEX [UNQ__UsrUser_Phone] ON [Usr].[User]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UNQ__UsrUser_Phone] ON [Usr].[User]
(
	[Phone] ASC
)
WHERE ([Phone] IS NOT NULL AND [Enabled] = 1)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UNQ__UsrUser_Email] ON [Usr].[User]
(
	[Email] ASC
)
WHERE ([Email] IS NOT NULL AND [Enabled] = 1)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

alter table [Usr].[User]
add [IsBot] bit NOT NULL default 0
go

update [Usr].[User] set [IsBot] = 1 where [Id] = '00000000-0000-0000-0000-000000000000';
go