USE [master]
GO

/****** Object:  Database [FLChat]    Script Date: 13.03.2019 14:35:56 ******/
CREATE DATABASE [FLChat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FLChat', FILENAME = N'D:\Projects\_db\MSSQL\MSSQL13.MSSQLSERVER\MSSQL\DATA\FLChat.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FLChat_log', FILENAME = N'D:\Projects\_db\MSSQL\MSSQL13.MSSQLSERVER\MSSQL\DATA\FLChat_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [FLChat] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FLChat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FLChat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FLChat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FLChat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FLChat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FLChat] SET ARITHABORT OFF 
GO

ALTER DATABASE [FLChat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FLChat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FLChat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FLChat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FLChat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FLChat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FLChat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FLChat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FLChat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FLChat] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FLChat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FLChat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FLChat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FLChat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FLChat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FLChat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FLChat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FLChat] SET RECOVERY FULL 
GO

ALTER DATABASE [FLChat] SET  MULTI_USER 
GO

ALTER DATABASE [FLChat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FLChat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FLChat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FLChat] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FLChat] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FLChat] SET QUERY_STORE = OFF
GO

USE [FLChat]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [FLChat] SET  READ_WRITE 
GO


